version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
